view: user_order_facts {
  derived_table: {
    explore_source: orders {
      column: user_id { field: orders.user_id }
      column: lifetime_order_count { field: orders.count }
      column: total_revenue { field: orders.total_revenue }
    }
  }

  dimension: user_id {
    primary_key: yes
    hidden: yes
    type: number
    sql: ${TABLE}.user_id ;;
  }

  dimension: lifetime_order_count {
    type: number
    label: "Lifetime Order Count"
    description: "Total number of orders placed by this customer over their lifetime."
    sql: ${TABLE}.lifetime_order_count ;;
  }

  dimension: total_revenue {
    type: number
    label: "Lifetime Total Revenue"
    description: "Total revenue generated by this customer over their lifetime."
    value_format_name: usd
    sql: ${TABLE}.total_revenue ;;
  }

  set: allowed_fields {
    fields: [
      user_id,
      lifetime_order_count,
      total_revenue
    ]
  }
}
